### ISSUE TITLE
Adding SDL_mixer 2.0 APIs

### ISSUE THREAD

**Issue by mikkun** [mikkun/gawk-sdl2#1]
## Description

Add the following SDL_mixer 2.0 APIs to gawk-sdl2:

- `Mix_AllocateChannels`
- `Mix_FreeMusic`
- `Mix_GetError`
- `Mix_HaltMusic`
- `Mix_Linked_Version`
- `Mix_LoadMUS`
- `Mix_PlayMusic`
- `Mix_Playing`
- `Mix_PlayingMusic`
- `Mix_QuerySpec`
- `Mix_SetDistance`
- `Mix_SetMusicCMD`
- `Mix_SetMusicPosition`
- `Mix_SetPosition`
- `Mix_SetReverseStereo`
- `Mix_VolumeMusic`

## Tasks

- [x] Implement `Mix_AllocateChannels`
- [x] Implement `Mix_FreeMusic`
- [x] Implement `Mix_GetError`
- [x] Implement `Mix_HaltMusic`
- [x] Implement `Mix_Linked_Version`
- [x] Implement `Mix_LoadMUS`
- [x] Implement `Mix_PlayMusic`
- [x] Implement `Mix_Playing`
- [x] Implement `Mix_PlayingMusic`
- [x] Implement `Mix_QuerySpec`
- [x] Implement `Mix_SetDistance`
- [x] Implement `Mix_SetMusicCMD`
- [x] Implement `Mix_SetMusicPosition`
- [x] Implement `Mix_SetPosition`
- [x] Implement `Mix_SetReverseStereo`
- [x] Implement `Mix_VolumeMusic`
- [x] Update documentation
