### ISSUE TITLE
Converting `SDL_Surface` struct to assoc array

### ISSUE THREAD

**Issue by mikkun** [mikkun/gawk-sdl2#2]
## Overview

Converting an `SDL_Surface` structure to an associative array.

## Purpose

Accessing an `SDL_Surface` structure in gawk.

## Tasks

- [x] Implement `SDL_Gawk_SurfaceToArray`
- [x] Implement `SDL_Gawk_PixelFormatToArray`
- [x] Create a sample script
- [x] Update documentation
