### ISSUE TITLE
Adding SDL 2.0 APIs

### ISSUE THREAD

**Issue by mikkun** [mikkun/gawk-sdl2#3]
## Description

Add the following SDL 2.0 APIs to gawk-sdl2:

- `SDL_AllocFormat`
- `SDL_FreePalette`
- `SDL_SetSurfacePalette`
- Implement more functions as needed

## Tasks

- [x] Implement `SDL_AllocFormat`
- [x] Implement `SDL_FreePalette`
- [x] Implement `SDL_SetSurfacePalette`
- [x] Implement more functions as needed
- [x] Update documentation
